### ISSUE TITLE
Remain in screen

### ISSUE THREAD

**Issue by hotpxl** [Availity/react-block-ui#14]
Current the dots are absolute 50% from the container it is in. But if the container is too high the dots may appear off-screen. Is there any way to make sure that when the container is high, at least the dots would not disapper?

**Comment by hotpxl** [comment]
Specifically, I have a tall div that spawns multiple pages. When it is loading, i would like to see dots as long as parts of the div is on screen. Of course, when the whole div is off screen, no dots are needed.

**Comment by TheSharpieOne** [comment]
I like the idea, my only concern is that the solution may be too heavy for this little project. I want to keep the size of this project as small as possible. I originally has javascript animations for the included loader to better support older browsers, but removed them in favor of CSS animations to shrink the package from ~30k to ~5k (because deps like `raf` and `bezier-easing` to help the animations were no longer needed)
If the solution is not that large, it can be integrated directly into the project. If it is rather big then maybe a custom loader which knows how to center itself could be created and used. If that is the case, a separate project (maybe "react-block-ui-extras" can be create for it (and probably move the redux stuff there as well)) just to keep this project light while providing out-of-a-different-box solution for this.

**Comment by hotpxl** [comment]
I'm totally unfamiliar with CSS. So this is not doable with purely css, right?

**Comment by TheSharpieOne** [comment]
Yeah, most likely not doable with only CSS. It may be a combination of JS and CSS, or just JS.
