### ISSUE TITLE
aria-busy renders "0" on screen

### ISSUE THREAD

**Issue by nylon22** [Availity/react-block-ui#23]
version: `1.1.3`

the following is rendering on the DOM when using `BlockUi` component:

```html
<div aria-busy="0">0<div>
```

code:
```jsx
 <BlockUi keepInView tag="div" blocking={blocking} message={message}>
      {children}
    </BlockUi>
```

How can I stop the "0" from rendering on screen?

**Comment by TheSharpieOne** [comment]
It seems like you are passing an int/number instead of a boolean for the value of the `blocking` prop. You are probably also getting warning in the console (in dev mode) indicating that you are sending the wrong type. `blocking` expects `true`/`false`, but it looks like you are sending `0` as indiacted by the `0` you are seeing and the `0` which appears as the value of `aria-busy`.
https://github.com/Availity/react-block-ui/blob/4ad71078c11b8bc2af4c4ec5bf2c1e476072b1af/src/BlockUi.js#L152-L154

You can do the following to covert the value to a boolean:
```jsx
 <BlockUi keepInView tag="div" blocking={!!blocking} message={message}>
      {children}
    </BlockUi>
```

**Comment by nylon22** [comment]
d'oh - good catch. I should've figured that out. Thanks @TheSharpieOne !
