### ISSUE TITLE
Elements in a blocked area should not accept actions triggered by the keyboard

### ISSUE THREAD

**Issue by asfernandes** [Availity/react-block-ui#4]
If I click a button and block its parent, I may still click the button it with space or enter keys.

Also, I may navigate with tab to the elements inside the blocked area.

It should block all user's interactions with the children components, not only mouse actions.

**Comment by TheSharpieOne** [comment]
This turned out to be an interesting problem. Serval over libraries which do the same/similar this as this using different frameworks/libraries (jquery, angular) have this same issue.
Currently (locally, to fix this issue) I have it so the elements cannot be tabbed in and such. This prevents the user from getting to a button in the first place; making space/enter actions not matter. But... I would like to effectively have the user tab/skip over the blocked ui, but that is a little more involved as I would have to determine which element would gain the focus or do some magic to trick the browser into doing that.

**Comment by asfernandes** [comment]
I had developed a custom solution on top of BlockUi for my specific problem, but it can be generalized.

Before the blocked content, I put two "invisible" inputs. When the block happens, I put the focus on the first input. The second input, when receives focus, focus the first input again. Two inputs are put after the blocked area for the same thing.

With some set of invisible inputs, you can build navigation that skips the blocked area. Some logic should be build to restore the focus if the user did not navigated from the control that had focus before the block happened.

**Comment by TheSharpieOne** [comment]
I have a solution, no need for extra hidden input. The user will also be able to tab around the blocked area (instead of acting like a wall preventing keyboard users from getting to the other side).
I need to create a few tests as well as handle returning focus. I'll try to finish up and create a release Monday.

**Comment by asfernandes** [comment]
Great!

**Comment by TheSharpieOne** [comment]
Ok, 0.2.3 should fix this issue. A new example was added to the docs, check it out.

On a side note... testing this was/is difficult. I could not figure out how to mock the focus with jsdom so that I could test various combinations... thus my test coverage went down...

**Comment by asfernandes** [comment]
Very very good! I'll test as soon as I can in my code and report back.

**Comment by asfernandes** [comment]
It works perfectly in my project. Thank you for the good project and the improvement.
