### ISSUE TITLE
keepInView start working after scroll

### ISSUE THREAD

**Issue by mzientkowski** [Availity/react-block-ui#47]
https://stackblitz.com/edit/react-block-ui?file=Example.js

![2019-10-17 12 15 49](https://user-images.githubusercontent.com/11761135/67000318-ea3cd180-f0d7-11e9-8803-8f21b04acbea.gif)

Like you see above KeepInView start working after using scroll and next blocking works correctly.
Do you have any idea to solve this problem ?

**Comment by TheSharpieOne** [comment]
This probably related to the changes in #27. Previous, to determine the size/area being blocked we were using a ref on the wrapper element, which is always render.
After that change, we are using the overlay element to determine the size/area being blocked. While it ends up being the same size/area, it is conditionally render (only rendered when blocking). When the blocking first activates, the code tries to get the measurements, but the overlay element isn't rendered yet so [`this.container`](https://github.com/Availity/react-block-ui/blob/84153c0319d7b746310108f259b878d230598494/src/BlockUi.js#L108) is `null` and the logic to aligning the loading indicator is skipped.
Scrolling causes that same logic to run again, but this time the overlay element has rendered and `this.container` is now a real reference.

It seems like we would need to add another wrapper element, one that is always there and that cannot be controlled by the user (the user wouldn't not be able to change the Tag/component rendered) so that the ref will always work.

**Comment by sanju-developer** [comment]
Hello guys, when this will be fixed :(
