### ISSUE TITLE
Use Portal for span in BlockUI to prevent validateDomNesting warnings

### ISSUE THREAD

**Issue by nylon22** [Availity/react-block-ui#49]
`<BlockUI />` renders a `<span>` to the DOM to use as a `ref`. See here: https://github.com/Availity/react-block-ui/blob/e5e2d0c22e5c855f7957b890c3ae8c91d9d6602c/src/BlockUi.js#L175

This can cause `validateDomNesting`warnings in certain situations. Take this situation for example:

```jsx
// ...
<table>
  <thead>
    <tr>
      <th>Header</th>
    </tr>
  </thead>
  <BlockUi tag="tbody">
    <tr>
      <td>row</td>
    </tr>
    // BlockUi renders a span here as a ref which is not a valid child of tbody
  </BlockUi>
</table>
```
*Suggested Solution*

Using `ReactDOM.createPortal`, render that `<span>` to the `body` tag of the `document` instead of as a child of the BlockUI's `tag`

**Comment by TheSharpieOne** [comment]
The proposed solution will break the usage. The reason that span exists is to get a reference to its parent, which currently is the "root"/wrapping DOM element for  the blocked section. Moving it out will break the DOM traversal (its parent would become `body`).

The reason we are going through this round-about way of getting a ref to the "root"/wrapping DOM element is because we cannot add a ref to the "root"/wrapping component/element as sometimes that thing is a reference to an instance of a component and not a DOM element. See #8.
Yes, forwardRef exists now, but we cannot expect every component to implement it (plus something a ref is supposed to reference the instance of the component).

Understanding why it exists and its intent, is there another solution to #8 which doesn't involve injecting a "random" DOM element? If so, we can simply implement that and remove this superfluous element.

That said... all of the other elements which make the actual loader and loading message (`.block-ui-container`) probably need to be in a portal so _they_ don't end up nested directly within a table. The difficult there is that will affect tab order which will break the focus management that prevent the user from tabbing into the blocked area. (we "bookend" the blocked content with focus catchers which, when focused, will skip the focus over the blocked content. If you are tabbing through and focus lands on the top element before the blocked content, we put focus on the bottom element after the blocked content. Similar, but reverse for shift-tab)

**Comment by nylon22** [comment]
> Or we can just not support having blockUi as a child within table elements

Thanks for feedback 🙌 . I can get around the issue I'm having pretty easily by resolving this issue: https://github.com/Availity/availity-react/issues/372
