### ISSUE TITLE
PropTypes is deprecated in React 15.5

### ISSUE THREAD

**Issue by caiorg** [Availity/react-block-ui#9]
I was fiddling around upgrading my React project's packages to their latest versions, including React itself, and as I finished the process and ran `npm start`, I've got the following warning on the console:

![captura de tela 2017-04-14 as 18 04 30](https://cloud.githubusercontent.com/assets/2515035/25056088/04de2600-213d-11e7-88c9-4087448a89a5.png)

As you can see, the warning is being generated by this component. So I just wanted to let you guys know about this issue.

Cheers

**Comment by edward93** [comment]
Also I get error when using BlockUi. It might be due to the latest react version.
```
Uncaught Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object. Check the render method of 'LoginComponent'
```

**Comment by TheSharpieOne** [comment]
I'll address the deprecations when I get some time. There is no rush since they are just warning. As for your other error, what object is being returned? Can you recreate this using webpackbin or something to share?

**Comment by caiorg** [comment]
@TheSharpieOne thx! I just wanted to point out this exists and know that they are on your radar.
As I've said, I was just playing with the latest versions to see how they behave.

**Comment by TheSharpieOne** [comment]
@caiorg the deprecations have been resolved. Since it was more of an internal/chore type of change, a patch semvar version has been release (0.2.5 -> 0.2.6) It doesn't a breaking the existing API exposed by this library.... that being said, some other libraries and people are experiencing issues with running on version prior to react 15.5 due to how react and prop-types work...

@edward93, as for your issue, `LoginComponent` is the only thing mentioned. Please create a new issue and provide a code example of your issue.

**Comment by caiorg** [comment]
@TheSharpieOne thx a lot for your fast response! 😀

**Comment by edward93** [comment]
@TheSharpieOne Hi sorry for late response. I didn't have time to look at the comments. 
Unfortunately I created my own component for that matter and I'm using this specific one but I will try to test it again and tell you the results if it fails I will open new issue and will share some basic code.
